var GAME_LEVELS = [
  ["                                                                                ",
   "  x                                                                         xx  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x   !@               xx      xx                           xx            z  x  ",
   "  x    xx          xx                xx               xx                  x  x  ",
   "  x          xx                                 xx               xx    xx    x  ",
   "  x                                        xx                                x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",  
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                            x                                                 ",
   "                                                            x                                                 ",
   "   x                                                        x                                                 ",
   "   x           xxx                  x                       x                                                 ",
   "   !@                               x                      zx                                                 ",
   "   xxx                              x             x!!!!!!!xxx                                                 ",
   "   x                                x         x   x                                                           ",
   "   x      xx   |||                  x       x     x                                                           ",
   "   x                                x     x       x                                                           ",
   "   x!!!!!!!!!!!xxx  x!!!!!!!!!!!xxxx              x                                                           ",
   "                  x                      x        x                                                           ",
   "                  x                   xx          x                                                           ",
   "                  xxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!x                                                           ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "  xxx                                                                                                    xxx  ",
   "  x                            xxxxxxxxxxx                                                                 x  ",
   "  x                                                                      x                                 x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                    z   x  ",
   "  x                                                                                                    x   x  ",
   "  x                                                                                                  x     x  ",
   "  x                                                                     x x               x      x         x  ",
   "  x                                                        x           xx xx        x                      x  ",
   "  !@      x       x            |||||||||||         x                  xx   xx  x                           x  ",
   " xxxx!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!x!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!xxx  |   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                           xxxx      x       x  xxxx      x                   ",
   "                                                           x        x x     x   x   x     x                   ",
   "                                                  x        xxxx    x   x   x    x   x     x                   ",
   "                                                  x        x      x     x x     x   x                         ",
   "                                                  x        xxxx  x       x      xxxx      x                   ",
   "                                                  x                                                           ",
   "                                                  x                                                           ",
   "                                                  x                                                           ",
   "                                                  x                                                           ",
   "                                                  x @                                                          ",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;